apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "False"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@192.168.0.105:5400/test_k8s"
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "REPLACE_ME"