apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 90
  template:
    spec:
      containers:
        - name: django-service
          image: django_app:latest
          command: ["python", "manage.py", "migrate", "--no-input"]
          envFrom:
            - configMapRef:
                name: django-config
          imagePullPolicy: Never
      restartPolicy: Never
